import path from "node:path";

import { defineConfig } from "vitest/config";

export default defineConfig({
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "./src"),
      "@mobile-contracts": path.resolve(__dirname, "./packages/mobile-contracts/src/index.ts"),
    },
  },
  test: {
    coverage: {
      provider: "v8",
      reporter: ["text", "text-summary", "json-summary", "lcov"],
      reportsDirectory: "./coverage",
      include: [
        "src/proxy.ts",
        "src/app/api/admin/media/**/*.{ts,tsx}",
        "src/app/api/admin/member-import/**/*.{ts,tsx}",
        "src/app/api/auth/**/*.{ts,tsx}",
        "src/app/api/cart/**/*.{ts,tsx}",
        "src/app/api/contact/**/*.{ts,tsx}",
        "src/app/api/dashboard/members/import/**/*.{ts,tsx}",
        "src/app/api/dashboard/membership-qr/validate/**/*.{ts,tsx}",
        "src/app/api/member-account/**/*.{ts,tsx}",
        "src/app/api/members/register/**/*.{ts,tsx}",
        "src/app/api/leads/**/*.{ts,tsx}",
        "src/lib/api-utils.ts",
        "src/lib/auth.ts",
        "src/lib/cookie-policy.ts",
        "src/lib/cart/**/*.{ts,tsx}",
        "src/lib/commerce/**/*.{ts,tsx}",
        "src/lib/data/member-import.ts",
        "src/lib/data/modules.ts",
        "src/lib/data/store.ts",
        "src/lib/data/store-admin/medusa-repository.ts",
        "src/lib/media/optimize-image.ts",
        "src/lib/security/**/*.{ts,tsx}",
        "src/lib/user-roles.ts",
        "src/lib/validators/**/*.{ts,tsx}",
      ],
      exclude: [
        "src/**/*.d.ts",
        "src/**/*.test.{ts,tsx}",
        "src/**/__tests__/**",
        "src/lib/supabase/database.types.ts",
        "src/lib/data/default-*.ts",
        "src/lib/medusa/**/*-types.ts",
      ],
      thresholds: {
        statements: 60,
        functions: 60,
        lines: 60,
        branches: 50,
        "src/lib/security/csp.ts": { lines: 80, branches: 80 },
        "src/lib/media/optimize-image.ts": { lines: 80, branches: 80 },
        "src/lib/validators/gym-members.ts": { lines: 80, branches: 80 },
      },
    },
    exclude: [
      "apps/mobile/**",
      "apps/medusa/**",
      "**/node_modules/**",
      "node_modules/**",
      "tests/e2e/**",
      "playwright.config.ts",
      "playwright-report/**",
      "test-results/**",
    ],
    environment: "node",
    globals: true,
    setupFiles: "./vitest.setup.ts",
  },
});
